# Site settings
title: Jesse Higson
name: Jesse Higson
logo: /img/logo.svg
email: jessehigson@gmail.com
baseurl: ''
url: ''
cdn_url: ''
environment: production

keep_files:
  - assets

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package-lock.json
  - package.json
  - README.md
  - serverupdate.sh
  - tags
  - vendor
  - yarn.lock

# Include a couple plugins
gems:
  - jekyll-sitemap
